from __future__ import annotations

from datetime import datetime
from typing import Iterable, Any

from sqlalchemy.orm import Session

from backend import models


def _parse_due_date(raw: Any) -> datetime:
    value = str(raw or datetime.now().strftime('%Y-%m-%d')).strip()
    try:
        return datetime.strptime(value[:10], '%Y-%m-%d')
    except ValueError as exc:
        raise ValueError("Date d'échéance invalide") from exc


def _signature(label: str, amount: float, due_date: datetime) -> tuple[str, float, str]:
    return (str(label or 'Échéance').strip(), round(float(amount), 2), due_date.date().isoformat())


def reconcile_document_installments(
    db: Session,
    *,
    patient_id: int,
    anchor_acte_id: int,
    total_amount: float,
    installments: Iterable[dict[str, Any]],
) -> models.InstallmentPlan:
    """Reconcile one global payment plan without duplicating paid history.

    The first active Acte generated by the document is the stable anchor. Paid or
    partially paid installments are immutable. Pending installments are updated in
    place, extra historical pending rows are marked ANNULE, and future expansion
    creates fresh rows instead of resurrecting cancelled history.
    """
    incoming = []
    for raw in installments:
        label = str(raw.get('label') or 'Échéance').strip()
        amount = float(raw.get('amount', 0))
        if amount <= 0:
            raise ValueError("Le montant d'une échéance doit être strictement positif")
        due_date = _parse_due_date(raw.get('date') or raw.get('dueDate'))
        incoming.append({
            'label': label,
            'amount': amount,
            'due_date': due_date,
            'notes': '{"sendReminder": true}' if raw.get('sendReminder', False) else None,
        })

    plan = (
        db.query(models.InstallmentPlan)
        .filter(models.InstallmentPlan.acte_id == anchor_acte_id)
        .order_by(models.InstallmentPlan.id.asc())
        .first()
    )
    if plan is None:
        plan = models.InstallmentPlan(
            patient_id=patient_id,
            acte_id=anchor_acte_id,
            title=f"Plan de paiement - {datetime.now().strftime('%d/%m/%Y')}",
            total_amount=float(total_amount),
        )
        db.add(plan)
        db.flush()
    else:
        if plan.patient_id != patient_id:
            raise ValueError("L'échéancier lié n'appartient pas à ce patient")
        plan.total_amount = float(total_amount)

    existing = sorted(list(plan.installments), key=lambda row: row.id or 0)
    immutable = [row for row in existing if str(row.status or '').upper() in {'PAYE', 'PARTIEL'}]
    pending = [row for row in existing if str(row.status or 'EN_ATTENTE').upper() == 'EN_ATTENTE']

    # A paid/partial row must still be represented exactly in the edited schedule.
    # This prevents a document edit from rewriting settled financial history.
    unmatched = list(incoming)
    for row in immutable:
        sig = _signature(row.label, row.amount, row.due_date)
        match_index = next(
            (idx for idx, item in enumerate(unmatched)
             if _signature(item['label'], item['amount'], item['due_date']) == sig),
            None,
        )
        if match_index is None:
            raise ValueError("Une échéance déjà réglée ou partiellement réglée ne peut pas être modifiée ni supprimée")
        unmatched.pop(match_index)

    for index, item in enumerate(unmatched):
        if index < len(pending):
            row = pending[index]
            row.label = item['label']
            row.amount = item['amount']
            row.due_date = item['due_date']
            row.notes = item['notes']
            row.status = 'EN_ATTENTE'
        else:
            db.add(models.Installment(
                plan_id=plan.id,
                label=item['label'],
                amount=item['amount'],
                due_date=item['due_date'],
                status='EN_ATTENTE',
                notes=item['notes'],
            ))

    for stale in pending[len(unmatched):]:
        stale.status = 'ANNULE'

    db.flush()
    return plan
