from backend.services.cephalo_measure_registry import CANONICAL_MEASUREMENTS

def test_new_steiner_geometry_is_covered_but_explicit_identity_gated():
    expected={
      "M_SND_DEG_V1":"GEOMETRY_COVERED_EXPLICIT_STEINER_D_REQUIRED",
      "M_POG_NB_MM_V1":"GEOMETRY_COVERED_EXPLICIT_IDENTITY_REQUIRED",
      "M_U1_NA_MM_V1":"GEOMETRY_COVERED_EXPLICIT_CROWN_SURFACE_REQUIRED",
      "M_L1_NB_MM_V1":"GEOMETRY_COVERED_EXPLICIT_CROWN_SURFACE_REQUIRED",
      "M_L1_GOGN_DEG_V1":"GEOMETRY_COVERED",
      "M_OCCLUSAL_PLANE_SN_DEG_V1":"GEOMETRY_COVERED_EXPLICIT_STEINER_ANCHORS_REQUIRED",
      "M_L1_DLINE_MM_V1":"GEOMETRY_COVERED_EXPLICIT_STEINER_D_AND_CROWN_REQUIRED",
      "M_L1_DLINE_DEG_V1":"GEOMETRY_COVERED_EXPLICIT_STEINER_D_REQUIRED",
    }
    for mid,status in expected.items():
        assert CANONICAL_MEASUREMENTS[mid].source_status==status
