"""remove_color_ref_and_init_lab_jobs

Revision ID: 0ac66fa0bdb8
Revises: 
Create Date: 2026-05-28 02:43:22.848351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac66fa0bdb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_act_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_act_catalog_id'), 'clinical_act_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_act_catalog_name'), 'clinical_act_catalog', ['name'], unique=True)
    op.create_table('clinical_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_clinical_categories_id'), 'clinical_categories', ['id'], unique=False)
    op.create_table('clinical_contraindications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('antecedent', sa.String(length=100), nullable=False),
    sa.Column('molecule', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_contraindications_antecedent'), 'clinical_contraindications', ['antecedent'], unique=False)
    op.create_index(op.f('ix_clinical_contraindications_id'), 'clinical_contraindications', ['id'], unique=False)
    op.create_table('clinical_drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('molecule', sa.String(length=100), nullable=False),
    sa.Column('brand_names', sa.JSON(), nullable=False),
    sa.Column('dosages', sa.JSON(), nullable=False),
    sa.Column('form', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_drugs_id'), 'clinical_drugs', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_drugs_molecule'), 'clinical_drugs', ['molecule'], unique=True)
    op.create_table('clinical_protocols_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure', sa.String(length=100), nullable=False),
    sa.Column('molecules', sa.JSON(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_protocols_db_id'), 'clinical_protocols_db', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_protocols_db_procedure'), 'clinical_protocols_db', ['procedure'], unique=True)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('forme', sa.String(length=50), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_index(op.f('ix_medications_nom'), 'medications', ['nom'], unique=True)
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_revoked_tokens_expires_at'), 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DENTISTE', 'SECRETAIRE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_licensed', sa.Boolean(), nullable=False),
    sa.Column('license_expires_at', sa.DateTime(), nullable=True),
    sa.Column('nom_complet', sa.String(length=255), nullable=True),
    sa.Column('specialites', sa.Text(), nullable=True),
    sa.Column('adresse_complete', sa.Text(), nullable=True),
    sa.Column('telephone_fixe', sa.String(length=20), nullable=True),
    sa.Column('telephone_mobile', sa.String(length=20), nullable=True),
    sa.Column('identifiants_legaux', sa.JSON(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employer_id'), 'users', ['employer_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_employer_id'), 'audit_logs', ['employer_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cabinet_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('nom_cabinet', sa.String(length=255), nullable=False),
    sa.Column('nom_praticien', sa.String(length=255), nullable=False),
    sa.Column('nom_praticien_ar', sa.String(length=255), nullable=False),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('letterhead_path', sa.String(length=500), nullable=True),
    sa.Column('header_lines_fr', sa.JSON(), nullable=False),
    sa.Column('header_lines_ar', sa.JSON(), nullable=False),
    sa.Column('specialty_ids', sa.JSON(), nullable=False),
    sa.Column('footer_address', sa.Text(), nullable=False),
    sa.Column('footer_phones', sa.String(length=255), nullable=False),
    sa.Column('ice', sa.String(length=50), nullable=True),
    sa.Column('if_', sa.String(length=50), nullable=True),
    sa.Column('inpe', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('font_fr', sa.String(length=50), nullable=False),
    sa.Column('font_ar', sa.String(length=50), nullable=False),
    sa.Column('watermark_enabled', sa.Boolean(), nullable=False),
    sa.Column('watermark_opacity', sa.Float(), nullable=False),
    sa.Column('margin_top', sa.Float(), nullable=False),
    sa.Column('margin_bottom', sa.Float(), nullable=False),
    sa.Column('is_initialized', sa.Boolean(), nullable=False),
    sa.Column('selected_theme', sa.String(length=20), nullable=False),
    sa.Column('app_accent_color', sa.String(length=7), nullable=True),
    sa.Column('selected_template', sa.String(length=20), nullable=False),
    sa.Column('cabinet_type', sa.Enum('PRIVE', 'CLINIQUE', name='cabinettype'), nullable=False),
    sa.Column('header_scale', sa.Float(), nullable=False),
    sa.Column('header_font_scale', sa.Float(), nullable=False),
    sa.Column('header_logo_scale', sa.Float(), nullable=False),
    sa.Column('header_line_height', sa.Float(), nullable=False),
    sa.Column('footer_font_scale', sa.Float(), nullable=False),
    sa.Column('footer_qr_scale', sa.Float(), nullable=False),
    sa.Column('footer_line_height', sa.Float(), nullable=False),
    sa.Column('contacts_json', sa.JSON(), nullable=True),
    sa.Column('qr_code_enabled', sa.Boolean(), nullable=False),
    sa.Column('qr_code_type', sa.Enum('NONE', 'VALIDATION', 'VCARD', 'WEBSITE', 'INSTAGRAM', 'PAYMENT', 'WHATSAPP', 'LOCATION', name='qrcodetype'), nullable=False),
    sa.Column('qr_code_value', sa.String(length=500), nullable=True),
    sa.Column('qr_code_color', sa.String(length=7), nullable=True),
    sa.Column('qr_code_label', sa.String(length=100), nullable=True),
    sa.Column('qr_code_style', sa.String(length=20), nullable=False),
    sa.Column('cloture_note_template', sa.Text(), nullable=False),
    sa.Column('cloture_devis_template', sa.Text(), nullable=False),
    sa.Column('show_patient_badges', sa.Boolean(), nullable=False),
    sa.Column('performance_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('clinical_tips_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('hide_header', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('hide_footer', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_index(op.f('ix_cabinet_configs_public_id'), 'cabinet_configs', ['public_id'], unique=True)
    op.create_table('clinical_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('variant_name', sa.String(length=100), nullable=False),
    sa.Column('medications_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['clinical_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_protocols_id'), 'clinical_protocols', ['id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token')
    )
    op.create_index(op.f('ix_device_tokens_employer_id'), 'device_tokens', ['employer_id'], unique=False)
    op.create_table('doctor_act_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('act_a', sa.String(length=255), nullable=False),
    sa.Column('act_b', sa.String(length=255), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_detected', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_act_correlations_act_a'), 'doctor_act_correlations', ['act_a'], unique=False)
    op.create_index(op.f('ix_doctor_act_correlations_act_b'), 'doctor_act_correlations', ['act_b'], unique=False)
    op.create_index(op.f('ix_doctor_act_correlations_doctor_id'), 'doctor_act_correlations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_act_correlations_id'), 'doctor_act_correlations', ['id'], unique=False)
    op.create_table('doctor_act_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('act_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_act_habits_act_name'), 'doctor_act_habits', ['act_name'], unique=False)
    op.create_index(op.f('ix_doctor_act_habits_doctor_id'), 'doctor_act_habits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_act_habits_id'), 'doctor_act_habits', ['id'], unique=False)
    op.create_table('doctor_medication_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('posologie', sa.String(length=255), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_medication_habits_doctor_id'), 'doctor_medication_habits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_medication_habits_id'), 'doctor_medication_habits', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_medication_habits_medication_name'), 'doctor_medication_habits', ['medication_name'], unique=False)
    op.create_table('doctor_prescription_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('act_code', sa.String(), nullable=False),
    sa.Column('drugs_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_prescription_preferences_act_code'), 'doctor_prescription_preferences', ['act_code'], unique=False)
    op.create_index(op.f('ix_doctor_prescription_preferences_id'), 'doctor_prescription_preferences', ['id'], unique=False)
    op.create_table('doctor_trigger_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('context_key', sa.String(length=100), nullable=False),
    sa.Column('action_suggestion', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_trigger_habits_doctor_id'), 'doctor_trigger_habits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_trigger_habits_id'), 'doctor_trigger_habits', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_trigger_habits_trigger_type'), 'doctor_trigger_habits', ['trigger_type'], unique=False)
    op.create_table('document_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('RAPPORT_CEPHALO', 'ORDONNANCE', 'CERTIFICAT', 'DEVIS', 'NOTE_HONORAIRES', 'LETTRE_MEDICALE', 'DOCUMENT_LIBRE', 'PHOTO_CLINIQUE', 'RADIOGRAPHIE', 'MOULAGE', 'BILAN', 'AUTRE', name='documenttype'), nullable=False),
    sa.Column('style_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('design_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_style_key'), 'document_templates', ['style_key'], unique=False)
    op.create_index(op.f('ix_document_templates_type'), 'document_templates', ['type'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_dossier', sa.String(length=20), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.DateTime(), nullable=False),
    sa.Column('sexe', sa.String(length=10), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('telephone_2', sa.String(length=20), nullable=True),
    sa.Column('telephone_3', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('assurance', sa.String(length=50), nullable=True),
    sa.Column('assurance_privee_nom', sa.String(length=100), nullable=True),
    sa.Column('assurance_complementaire', sa.Boolean(), nullable=False),
    sa.Column('assurance_complementaire_nom', sa.String(length=100), nullable=True),
    sa.Column('antecedents_medicaux', sa.String(), nullable=True),
    sa.Column('motif_consultation', sa.Text(), nullable=True),
    sa.Column('manual_grade', sa.String(length=20), nullable=True),
    sa.Column('grade_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_employer_id'), 'patients', ['employer_id'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_nom'), 'patients', ['nom'], unique=False)
    op.create_index(op.f('ix_patients_numero_dossier'), 'patients', ['numero_dossier'], unique=True)
    op.create_index(op.f('ix_patients_prenom'), 'patients', ['prenom'], unique=False)
    op.create_table('zka_pairing_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('master_key', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zka_pairing_tokens_expires_at'), 'zka_pairing_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_zka_pairing_tokens_token'), 'zka_pairing_tokens', ['token'], unique=True)
    op.create_table('actes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('praticien_id', sa.Integer(), nullable=False),
    sa.Column('type_acte', sa.Enum('SOIN', 'PROTHESE', 'ORTHO_SEMESTRE', 'ORTHO_CONTENTION', name='actetype'), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('statut_paiement', sa.Enum('EN_ATTENTE', 'PAYE', 'PARTIEL', 'A_ENCAISSER', name='paiementstatut'), nullable=False),
    sa.Column('is_accounted', sa.Boolean(), nullable=False),
    sa.Column('is_collected', sa.Boolean(), nullable=False),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['praticien_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actes_id'), 'actes', ['id'], unique=False)
    op.create_index(op.f('ix_actes_is_accounted'), 'actes', ['is_accounted'], unique=False)
    op.create_index(op.f('ix_actes_is_collected'), 'actes', ['is_collected'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('insight_content', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_employer_id'), 'ai_feedback', ['employer_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_patient_id'), 'ai_feedback', ['patient_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('datetime_start', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PREVU', 'EN_SALLE_ATTENTE', 'EN_FAUTEUIL', 'TERMINE', 'ANNULE', name='appointmentstatus'), nullable=False),
    sa.Column('scheduling_type', sa.Enum('EXACT_TIME', 'MORNING', 'AFTERNOON', 'FULL_DAY', name='schedulingtype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_datetime_start'), 'appointments', ['datetime_start'], unique=False)
    op.create_index(op.f('ix_appointments_employer_id'), 'appointments', ['employer_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('cephalo_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('image_original_path', sa.String(), nullable=False),
    sa.Column('landmarks_data', sa.JSON(), nullable=False),
    sa.Column('angles_data', sa.JSON(), nullable=False),
    sa.Column('is_calibrated', sa.Boolean(), nullable=False),
    sa.Column('mm_per_pixel', sa.Float(), nullable=True),
    sa.Column('calibration_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cephalo_analyses_id'), 'cephalo_analyses', ['id'], unique=False)
    op.create_table('dossiers_cliniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('is_ortho_active', sa.Boolean(), nullable=False),
    sa.Column('note_honnetete', sa.Text(), nullable=True),
    sa.Column('antecedents_medicaux', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_dossiers_cliniques_id'), 'dossiers_cliniques', ['id'], unique=False)
    op.create_table('installment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_plans_id'), 'installment_plans', ['id'], unique=False)
    op.create_table('panoramic_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('detections_data', sa.JSON(), nullable=False),
    sa.Column('report_narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panoramic_analyses_id'), 'panoramic_analyses', ['id'], unique=False)
    op.create_table('proactive_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proactive_alerts_created_at'), 'proactive_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_proactive_alerts_employer_id'), 'proactive_alerts', ['employer_id'], unique=False)
    op.create_index(op.f('ix_proactive_alerts_patient_id'), 'proactive_alerts', ['patient_id'], unique=False)
    op.create_table('document_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('RAPPORT_CEPHALO', 'ORDONNANCE', 'CERTIFICAT', 'DEVIS', 'NOTE_HONORAIRES', 'LETTRE_MEDICALE', 'DOCUMENT_LIBRE', 'PHOTO_CLINIQUE', 'RADIOGRAPHIE', 'MOULAGE', 'BILAN', 'AUTRE', name='documenttype'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('document_group_id', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_latest_version', sa.Boolean(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIF', 'SUPPRIME', 'ARCHIVE', name='documentstatus'), nullable=False),
    sa.Column('is_accounted', sa.Boolean(), nullable=False),
    sa.Column('payment_status', sa.Enum('EN_ATTENTE', 'PAYE', 'PARTIEL', 'A_ENCAISSER', name='paiementstatut'), nullable=False),
    sa.Column('is_collected', sa.Boolean(), nullable=False),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('permanent_delete_at', sa.DateTime(), nullable=True),
    sa.Column('clinical_data', sa.JSON(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['cephalo_analyses.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_archives_document_group_id'), 'document_archives', ['document_group_id'], unique=False)
    op.create_index(op.f('ix_document_archives_file_hash'), 'document_archives', ['file_hash'], unique=False)
    op.create_index(op.f('ix_document_archives_id'), 'document_archives', ['id'], unique=False)
    op.create_index(op.f('ix_document_archives_is_accounted'), 'document_archives', ['is_accounted'], unique=False)
    op.create_index(op.f('ix_document_archives_is_collected'), 'document_archives', ['is_collected'], unique=False)
    op.create_index(op.f('ix_document_archives_is_latest_version'), 'document_archives', ['is_latest_version'], unique=False)
    op.create_index(op.f('ix_document_archives_patient_id'), 'document_archives', ['patient_id'], unique=False)
    op.create_index(op.f('ix_document_archives_payment_status'), 'document_archives', ['payment_status'], unique=False)
    op.create_index(op.f('ix_document_archives_status'), 'document_archives', ['status'], unique=False)
    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installments_id'), 'installments', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.Enum('ESPECES', 'CARTE', 'VIREMENT', 'CHEQUE', name='paymentmethod'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('acte_id', sa.Integer(), nullable=True),
    sa.Column('installment_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['acte_id'], ['actes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_installments_id'), table_name='installments')
    op.drop_table('installments')
    op.drop_index(op.f('ix_document_archives_status'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_payment_status'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_patient_id'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_is_latest_version'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_is_collected'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_is_accounted'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_id'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_file_hash'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_document_group_id'), table_name='document_archives')
    op.drop_table('document_archives')
    op.drop_index(op.f('ix_proactive_alerts_patient_id'), table_name='proactive_alerts')
    op.drop_index(op.f('ix_proactive_alerts_employer_id'), table_name='proactive_alerts')
    op.drop_index(op.f('ix_proactive_alerts_created_at'), table_name='proactive_alerts')
    op.drop_table('proactive_alerts')
    op.drop_index(op.f('ix_panoramic_analyses_id'), table_name='panoramic_analyses')
    op.drop_table('panoramic_analyses')
    op.drop_index(op.f('ix_installment_plans_id'), table_name='installment_plans')
    op.drop_table('installment_plans')
    op.drop_index(op.f('ix_dossiers_cliniques_id'), table_name='dossiers_cliniques')
    op.drop_table('dossiers_cliniques')
    op.drop_index(op.f('ix_cephalo_analyses_id'), table_name='cephalo_analyses')
    op.drop_table('cephalo_analyses')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_employer_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_datetime_start'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_ai_feedback_patient_id'), table_name='ai_feedback')
    op.drop_index(op.f('ix_ai_feedback_employer_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_actes_is_collected'), table_name='actes')
    op.drop_index(op.f('ix_actes_is_accounted'), table_name='actes')
    op.drop_index(op.f('ix_actes_id'), table_name='actes')
    op.drop_table('actes')
    op.drop_index(op.f('ix_zka_pairing_tokens_token'), table_name='zka_pairing_tokens')
    op.drop_index(op.f('ix_zka_pairing_tokens_expires_at'), table_name='zka_pairing_tokens')
    op.drop_table('zka_pairing_tokens')
    op.drop_index(op.f('ix_patients_prenom'), table_name='patients')
    op.drop_index(op.f('ix_patients_numero_dossier'), table_name='patients')
    op.drop_index(op.f('ix_patients_nom'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_employer_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_document_templates_type'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_style_key'), table_name='document_templates')
    op.drop_table('document_templates')
    op.drop_index(op.f('ix_doctor_trigger_habits_trigger_type'), table_name='doctor_trigger_habits')
    op.drop_index(op.f('ix_doctor_trigger_habits_id'), table_name='doctor_trigger_habits')
    op.drop_index(op.f('ix_doctor_trigger_habits_doctor_id'), table_name='doctor_trigger_habits')
    op.drop_table('doctor_trigger_habits')
    op.drop_index(op.f('ix_doctor_prescription_preferences_id'), table_name='doctor_prescription_preferences')
    op.drop_index(op.f('ix_doctor_prescription_preferences_act_code'), table_name='doctor_prescription_preferences')
    op.drop_table('doctor_prescription_preferences')
    op.drop_index(op.f('ix_doctor_medication_habits_medication_name'), table_name='doctor_medication_habits')
    op.drop_index(op.f('ix_doctor_medication_habits_id'), table_name='doctor_medication_habits')
    op.drop_index(op.f('ix_doctor_medication_habits_doctor_id'), table_name='doctor_medication_habits')
    op.drop_table('doctor_medication_habits')
    op.drop_index(op.f('ix_doctor_act_habits_id'), table_name='doctor_act_habits')
    op.drop_index(op.f('ix_doctor_act_habits_doctor_id'), table_name='doctor_act_habits')
    op.drop_index(op.f('ix_doctor_act_habits_act_name'), table_name='doctor_act_habits')
    op.drop_table('doctor_act_habits')
    op.drop_index(op.f('ix_doctor_act_correlations_id'), table_name='doctor_act_correlations')
    op.drop_index(op.f('ix_doctor_act_correlations_doctor_id'), table_name='doctor_act_correlations')
    op.drop_index(op.f('ix_doctor_act_correlations_act_b'), table_name='doctor_act_correlations')
    op.drop_index(op.f('ix_doctor_act_correlations_act_a'), table_name='doctor_act_correlations')
    op.drop_table('doctor_act_correlations')
    op.drop_index(op.f('ix_device_tokens_employer_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_clinical_protocols_id'), table_name='clinical_protocols')
    op.drop_table('clinical_protocols')
    op.drop_index(op.f('ix_cabinet_configs_public_id'), table_name='cabinet_configs')
    op.drop_table('cabinet_configs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_employer_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_expires_at'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_medications_nom'), table_name='medications')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_clinical_protocols_db_procedure'), table_name='clinical_protocols_db')
    op.drop_index(op.f('ix_clinical_protocols_db_id'), table_name='clinical_protocols_db')
    op.drop_table('clinical_protocols_db')
    op.drop_index(op.f('ix_clinical_drugs_molecule'), table_name='clinical_drugs')
    op.drop_index(op.f('ix_clinical_drugs_id'), table_name='clinical_drugs')
    op.drop_table('clinical_drugs')
    op.drop_index(op.f('ix_clinical_contraindications_id'), table_name='clinical_contraindications')
    op.drop_index(op.f('ix_clinical_contraindications_antecedent'), table_name='clinical_contraindications')
    op.drop_table('clinical_contraindications')
    op.drop_index(op.f('ix_clinical_categories_id'), table_name='clinical_categories')
    op.drop_table('clinical_categories')
    op.drop_index(op.f('ix_clinical_act_catalog_name'), table_name='clinical_act_catalog')
    op.drop_index(op.f('ix_clinical_act_catalog_id'), table_name='clinical_act_catalog')
    op.drop_table('clinical_act_catalog')
    # ### end Alembic commands ###
