"""Add SuperAdmin features

Revision ID: 2872d2ae6349
Revises: 8f6465e49d90
Create Date: 2026-06-01 00:21:09.987311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2872d2ae6349'
down_revision: Union[str, None] = '8f6465e49d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_history_id'), 'license_history', ['id'], unique=False)
    op.create_index(op.f('ix_license_history_user_id'), 'license_history', ['user_id'], unique=False)
    op.alter_column('cabinet_configs', 'cabinet_type',
               existing_type=postgresql.ENUM('PRIVE', 'CLINIQUE', name='cabinettype'),
               nullable=False,
               existing_server_default=sa.text("'PRIVE'::cabinettype"))
    op.alter_column('document_archives', 'payment_status',
               existing_type=postgresql.ENUM('EN_ATTENTE', 'PAYE', 'PARTIEL', name='paiementstatut'),
               nullable=False,
               existing_server_default=sa.text("'EN_ATTENTE'::paiementstatut"))
    op.add_column('users', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('internal_notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'internal_notes')
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'is_archived')
    op.alter_column('document_archives', 'payment_status',
               existing_type=postgresql.ENUM('EN_ATTENTE', 'PAYE', 'PARTIEL', name='paiementstatut'),
               nullable=True,
               existing_server_default=sa.text("'EN_ATTENTE'::paiementstatut"))
    op.alter_column('cabinet_configs', 'cabinet_type',
               existing_type=postgresql.ENUM('PRIVE', 'CLINIQUE', name='cabinettype'),
               nullable=True,
               existing_server_default=sa.text("'PRIVE'::cabinettype"))
    op.drop_index(op.f('ix_license_history_user_id'), table_name='license_history')
    op.drop_index(op.f('ix_license_history_id'), table_name='license_history')
    op.drop_table('license_history')
    # ### end Alembic commands ###
