"""Sync DB and models after god file split and manual migrations

Revision ID: 8f6465e49d90
Revises: 0ac66fa0bdb8
Create Date: 2026-05-30 11:13:29.140722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f6465e49d90'
down_revision: Union[str, None] = '0ac66fa0bdb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factures_legales_id'), table_name='factures_legales')
    op.drop_index(op.f('ix_factures_legales_numero_sequence'), table_name='factures_legales')
    op.drop_table('factures_legales')
    op.alter_column('actes', 'is_accounted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('actes', 'is_collected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('actes', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_actes_date_debut'), table_name='actes')
    op.drop_index(op.f('idx_actes_patient_id'), table_name='actes')
    op.create_index(op.f('ix_actes_is_accounted'), 'actes', ['is_accounted'], unique=False)
    op.create_index(op.f('ix_actes_is_collected'), 'actes', ['is_collected'], unique=False)
    op.create_foreign_key(None, 'actes', 'users', ['praticien_id'], ['id'])
    op.drop_column('actes', 'code_ccam')
    op.drop_column('actes', 'date_fin')
    op.drop_index(op.f('idx_ai_feedback_employer'), table_name='ai_feedback')
    op.drop_index(op.f('idx_ai_feedback_patient'), table_name='ai_feedback')
    op.alter_column('appointments', 'scheduling_type',
               existing_type=postgresql.ENUM('EXACT_TIME', 'MORNING', 'AFTERNOON', 'FULL_DAY', name='schedulingtype'),
               nullable=False,
               existing_server_default=sa.text("'EXACT_TIME'::schedulingtype"))
    op.alter_column('appointments', 'reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('appointments', 'reminder_sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('appointments', 'employer_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_appointments_employer_date'), table_name='appointments')
    op.create_index(op.f('ix_appointments_employer_id'), 'appointments', ['employer_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'users', ['employer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cabinet_configs', 'nom_cabinet',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('cabinet_configs', 'nom_praticien',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('cabinet_configs', 'nom_praticien_ar',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('cabinet_configs', 'specialty_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('cabinet_configs', 'secondary_color',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'#1e40af'::character varying"))
    op.alter_column('cabinet_configs', 'accent_color',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'#60a5fa'::character varying"))
    op.alter_column('cabinet_configs', 'margin_top',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('3.6'))
    op.alter_column('cabinet_configs', 'margin_bottom',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('3.2'))
    op.alter_column('cabinet_configs', 'selected_theme',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'elite'::character varying"))
    op.alter_column('cabinet_configs', 'selected_template',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'classic'::character varying"))
    op.execute("ALTER TABLE cabinet_configs ALTER COLUMN cabinet_type DROP DEFAULT")
    op.execute("ALTER TABLE cabinet_configs ALTER COLUMN cabinet_type TYPE cabinettype USING cabinet_type::cabinettype")
    op.execute("ALTER TABLE cabinet_configs ALTER COLUMN cabinet_type SET DEFAULT 'PRIVE'")
    op.alter_column('cabinet_configs', 'header_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'header_font_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'header_logo_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'header_line_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'footer_font_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'footer_qr_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'footer_line_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'contacts_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.execute("ALTER TABLE cabinet_configs ALTER COLUMN qr_code_type DROP DEFAULT")
    op.execute("ALTER TABLE cabinet_configs ALTER COLUMN qr_code_type TYPE qrcodetype USING qr_code_type::qrcodetype")
    op.execute("ALTER TABLE cabinet_configs ALTER COLUMN qr_code_type SET DEFAULT 'VCARD'")
    op.alter_column('cabinet_configs', 'cloture_note_template',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'Arrêtée la présente note à la somme de {total_words} TTC ({total_amount} MAD).'::text"))
    op.alter_column('cabinet_configs', 'cloture_devis_template',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'Arrêté le présent devis à la somme de {total_words} TTC ({total_amount} MAD).'::text"))
    op.alter_column('cabinet_configs', 'show_patient_badges',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('cabinet_configs', 'performance_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cabinet_configs', 'clinical_tips_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('cabinet_configs', 'hide_header',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('cabinet_configs', 'hide_footer',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(None, 'cabinet_configs', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cephalo_analyses', 'is_calibrated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cephalo_analyses', 'calibration_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('cephalo_analyses', 'image_tracings_path')
    op.alter_column('document_archives', 'is_accounted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.execute("ALTER TABLE document_archives ALTER COLUMN payment_status DROP DEFAULT")
    op.execute("ALTER TABLE document_archives ALTER COLUMN payment_status TYPE paiementstatut USING payment_status::paiementstatut")
    op.execute("ALTER TABLE document_archives ALTER COLUMN payment_status SET DEFAULT 'EN_ATTENTE'")
    op.alter_column('document_archives', 'is_collected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_documents_patient_created'), table_name='document_archives')
    op.create_index(op.f('ix_document_archives_is_accounted'), 'document_archives', ['is_accounted'], unique=False)
    op.create_index(op.f('ix_document_archives_is_collected'), 'document_archives', ['is_collected'], unique=False)
    op.create_index(op.f('ix_document_archives_payment_status'), 'document_archives', ['payment_status'], unique=False)
    op.create_foreign_key(None, 'document_archives', 'users', ['uploaded_by_id'], ['id'])
    op.create_foreign_key(None, 'document_templates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('patients', 'employer_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('patients', 'assurance_complementaire',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('patients_numero_dossier_key'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_employer_id'), 'patients', ['employer_id'], unique=False)
    op.create_index(op.f('ix_patients_numero_dossier'), 'patients', ['numero_dossier'], unique=True)
    op.create_foreign_key(None, 'patients', 'users', ['employer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('ix_users_employer_id'), 'users', ['employer_id'], unique=False)
    op.alter_column('zka_pairing_tokens', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'DENTISTE'::character varying"))
    op.drop_index(op.f('idx_zka_tokens_expires'), table_name='zka_pairing_tokens')
    op.drop_index(op.f('idx_zka_tokens_token'), table_name='zka_pairing_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_zka_tokens_token'), 'zka_pairing_tokens', ['token'], unique=False)
    op.create_index(op.f('idx_zka_tokens_expires'), 'zka_pairing_tokens', ['expires_at'], unique=False)
    op.alter_column('zka_pairing_tokens', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'DENTISTE'::character varying"))
    op.drop_index(op.f('ix_users_employer_id'), table_name='users')
    op.alter_column('users', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_numero_dossier'), table_name='patients')
    op.drop_index(op.f('ix_patients_employer_id'), table_name='patients')
    op.create_unique_constraint(op.f('patients_numero_dossier_key'), 'patients', ['numero_dossier'])
    op.alter_column('patients', 'assurance_complementaire',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patients', 'employer_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'document_templates', type_='foreignkey')
    op.drop_constraint(None, 'document_archives', type_='foreignkey')
    op.drop_index(op.f('ix_document_archives_payment_status'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_is_collected'), table_name='document_archives')
    op.drop_index(op.f('ix_document_archives_is_accounted'), table_name='document_archives')
    op.create_index(op.f('idx_documents_patient_created'), 'document_archives', ['patient_id', 'created_at'], unique=False)
    op.alter_column('document_archives', 'is_collected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('document_archives', 'payment_status',
               existing_type=sa.Enum('EN_ATTENTE', 'PAYE', 'PARTIEL', 'A_ENCAISSER', name='paiementstatut'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'EN_ATTENTE'::character varying"))
    op.alter_column('document_archives', 'is_accounted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('cephalo_analyses', sa.Column('image_tracings_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('cephalo_analyses', 'calibration_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cephalo_analyses', 'is_calibrated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'cabinet_configs', type_='foreignkey')
    op.alter_column('cabinet_configs', 'hide_footer',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('cabinet_configs', 'hide_header',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('cabinet_configs', 'clinical_tips_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('cabinet_configs', 'performance_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('cabinet_configs', 'show_patient_badges',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('cabinet_configs', 'cloture_devis_template',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Arrêté le présent devis à la somme de {total_words} TTC ({total_amount} MAD).'::text"))
    op.alter_column('cabinet_configs', 'cloture_note_template',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Arrêtée la présente note à la somme de {total_words} TTC ({total_amount} MAD).'::text"))
    op.alter_column('cabinet_configs', 'qr_code_type',
               existing_type=sa.Enum('NONE', 'VALIDATION', 'VCARD', 'WEBSITE', 'INSTAGRAM', 'PAYMENT', 'WHATSAPP', 'LOCATION', name='qrcodetype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'VCARD'::character varying"))
    op.alter_column('cabinet_configs', 'contacts_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('cabinet_configs', 'footer_line_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'footer_qr_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'footer_font_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'header_line_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'header_logo_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'header_font_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'header_scale',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('cabinet_configs', 'cabinet_type',
               existing_type=sa.Enum('PRIVE', 'CLINIQUE', name='cabinettype'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'PRIVE'::character varying"))
    op.alter_column('cabinet_configs', 'selected_template',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'classic'::character varying"))
    op.alter_column('cabinet_configs', 'selected_theme',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'elite'::character varying"))
    op.alter_column('cabinet_configs', 'margin_bottom',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('3.2'))
    op.alter_column('cabinet_configs', 'margin_top',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('3.6'))
    op.alter_column('cabinet_configs', 'accent_color',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'#60a5fa'::character varying"))
    op.alter_column('cabinet_configs', 'secondary_color',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'#1e40af'::character varying"))
    op.alter_column('cabinet_configs', 'specialty_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('cabinet_configs', 'nom_praticien_ar',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('cabinet_configs', 'nom_praticien',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('cabinet_configs', 'nom_cabinet',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_employer_id'), table_name='appointments')
    op.create_index(op.f('idx_appointments_employer_date'), 'appointments', ['employer_id', 'datetime_start'], unique=False)
    op.alter_column('appointments', 'employer_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('appointments', 'reminder_sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('appointments', 'reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('appointments', 'scheduling_type',
               existing_type=postgresql.ENUM('EXACT_TIME', 'MORNING', 'AFTERNOON', 'FULL_DAY', name='schedulingtype'),
               nullable=True,
               existing_server_default=sa.text("'EXACT_TIME'::schedulingtype"))
    op.create_index(op.f('idx_ai_feedback_patient'), 'ai_feedback', ['patient_id'], unique=False)
    op.create_index(op.f('idx_ai_feedback_employer'), 'ai_feedback', ['employer_id'], unique=False)
    op.add_column('actes', sa.Column('date_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('actes', sa.Column('code_ccam', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'actes', type_='foreignkey')
    op.drop_index(op.f('ix_actes_is_collected'), table_name='actes')
    op.drop_index(op.f('ix_actes_is_accounted'), table_name='actes')
    op.create_index(op.f('idx_actes_patient_id'), 'actes', ['patient_id'], unique=False)
    op.create_index(op.f('idx_actes_date_debut'), 'actes', ['date_debut'], unique=False)
    op.alter_column('actes', 'attachments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('actes', 'is_collected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('actes', 'is_accounted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('factures_legales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero_sequence', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('montant_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date_emission', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_acquitee', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('factures_legales_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('factures_legales_pkey'))
    )
    op.create_index(op.f('ix_factures_legales_numero_sequence'), 'factures_legales', ['numero_sequence'], unique=True)
    op.create_index(op.f('ix_factures_legales_id'), 'factures_legales', ['id'], unique=False)
    # ### end Alembic commands ###
