import type { MobileSuperAdminPreviewData } from './useMobileSuperAdmin';

const now = Date.now();
const iso = (days: number) => new Date(now + days * 86_400_000).toISOString();

export const DEMO_SUPERADMIN: MobileSuperAdminPreviewData = {
  clients: [
    {
      id: 5001,
      nom_complet: 'Dr Amine Démo',
      email: 'amine.demo@example.test',
      cabinet_name: 'Cabinet Atlas Démo',
      is_active: true,
      is_licensed: true,
      license_expires_at: iso(48),
      is_archived: false,
      is_suspended: false,
      internal_notes: 'Client fictif — renouvellement annuel.',
      subscription_plan: 'ELITE',
      stats: { total_patients: 184, total_ia_panoramique: 31, total_ia_cephalo: 8 },
    },
    {
      id: 5002,
      nom_complet: 'Dr Lina Exemple',
      email: 'lina.exemple@example.test',
      cabinet_name: 'Clinique Horizon Test',
      is_active: true,
      is_licensed: true,
      license_expires_at: iso(9),
      is_archived: false,
      is_suspended: false,
      internal_notes: 'Donnée de preview uniquement.',
      subscription_plan: 'PREMIUM',
      stats: { total_patients: 92, total_ia_panoramique: 14, total_ia_cephalo: 3 },
    },
    {
      id: 5003,
      nom_complet: 'Dr Sami Fictif',
      email: 'sami.fictif@example.test',
      cabinet_name: 'Centre Dentaire Démonstration',
      is_active: true,
      is_licensed: true,
      license_expires_at: iso(120),
      is_archived: false,
      is_suspended: true,
      internal_notes: 'Compte fictif suspendu pour illustrer le statut.',
      subscription_plan: 'GOLD',
      stats: { total_patients: 45, total_ia_panoramique: 6, total_ia_cephalo: 0 },
    },
  ],
  trialCodes: [
    {
      id: 6101,
      code: 'DC-DEMO-42A1-8BC2',
      email: 'essai.actif@example.test',
      nom_complet: 'Praticien Essai Démo',
      cabinet_name: 'Cabinet Essai Démo',
      trial_days: 30,
      notes: 'Lien fictif.',
      expires_at: iso(12),
      consumed_at: null,
      revoked_at: null,
      activation_url: 'https://digitalcrown.local/activate?code=DC-DEMO-42A1-8BC2',
    },
    {
      id: 6102,
      code: 'DC-DEMO-OLD-7711',
      email: 'essai.archive@example.test',
      nom_complet: 'Praticien Archive Test',
      cabinet_name: 'Cabinet Archive Test',
      trial_days: 30,
      notes: 'Code fictif consommé.',
      expires_at: iso(4),
      consumed_at: iso(-2),
      revoked_at: null,
      activation_url: 'https://digitalcrown.local/activate?code=DC-DEMO-OLD-7711',
    },
  ],
  overview: {
    cabinetsCount: 7,
    suppliersCount: 5,
    activeSuppliersCount: 4,
    productsCount: 148,
    ordersCount: 23,
    ordersByStatus: { DRAFT: 4, SENT_TO_PARTNER: 3, MODIFIED_AFTER_SEND: 1, CONFIRMED: 5, FULFILLED: 9, CANCELLED: 1 },
    recognizedRevenueAmount: 18450,
    invoicedSupplierAmount: 126300,
    syncDegradedCount: 1,
    syncStaleCount: 1,
    activeAgreementsCount: 4,
  },
  globalOrders: [
    { employerId: 5001, ownerEmail: 'amine.demo@example.test', ownerName: 'Dr Amine Démo', id: 7001, orderNumber: 'CMD-PART-DEMO-7001', supplierName: 'Dental Supply Demo', status: 'DRAFT', currentTotal: 1240, recognizedRevenueAmount: 0, partnerReference: null },
    { employerId: 5002, ownerEmail: 'lina.exemple@example.test', ownerName: 'Dr Lina Exemple', id: 7002, orderNumber: 'CMD-PART-DEMO-7002', supplierName: 'MedStock Test', status: 'CONFIRMED', currentTotal: 2860, recognizedRevenueAmount: 286, partnerReference: 'SUP-TEST-8841' },
    { employerId: 5003, ownerEmail: 'sami.fictif@example.test', ownerName: 'Dr Sami Fictif', id: 7003, orderNumber: 'CMD-PART-DEMO-7003', supplierName: 'Dental Supply Demo', status: 'FULFILLED', currentTotal: 940, recognizedRevenueAmount: 94, partnerReference: 'SUP-TEST-7710' },
  ],
  suppliers: [
    { employerId: 5001, id: 801, supplierKey: 'dental-demo', name: 'Dental Supply Demo', badge: 'API', description: 'Fournisseur fictif.', promise: 'Preview locale.', apiBaseUrl: 'https://supplier.example.test', syncMode: 'api', isActive: true, productCount: 82 },
    { employerId: 5002, id: 802, supplierKey: 'medstock-test', name: 'MedStock Test', badge: 'Démo', description: 'Fournisseur fictif dégradé.', promise: 'Preview locale.', apiBaseUrl: null, syncMode: 'manual', isActive: true, productCount: 66 },
  ],
  products: [
    { employerId: 5001, id: 901, supplierId: 801, supplierName: 'Dental Supply Demo', name: 'Composite universel Démo', sku: 'CMP-DEMO-01', dentalCategory: 'Restauration', dentalSpecialty: 'Omnipratique', unit: 'seringue', price: 390, availability: 'AVAILABLE', shortDescription: 'Produit fictif.', longDescription: 'Aucune donnée fournisseur réelle.', isFeatured: true, sortOrder: 1 },
    { employerId: 5001, id: 902, supplierId: 801, supplierName: 'Dental Supply Demo', name: 'Limes NiTi Test', sku: 'NITI-TEST-06', dentalCategory: 'Endodontie', dentalSpecialty: 'Endodontie', unit: 'blister', price: 295, availability: 'AVAILABLE', shortDescription: 'Produit fictif.', longDescription: 'Aucune donnée fournisseur réelle.', isFeatured: false, sortOrder: 2 },
    { employerId: 5002, id: 903, supplierId: 802, supplierName: 'MedStock Test', name: 'Gants nitrile Preview', sku: 'NIT-PREVIEW-M', dentalCategory: 'Consommables', dentalSpecialty: 'Omnipratique', unit: 'boîte', price: 78, availability: 'ON_REQUEST', shortDescription: 'Produit fictif.', longDescription: 'Aucune donnée fournisseur réelle.', isFeatured: false, sortOrder: 3 },
  ],
  incidents: [
    { employerId: 5002, ownerEmail: 'lina.exemple@example.test', ownerName: 'Dr Lina Exemple', supplierId: 802, supplierName: 'MedStock Test', freshness: { status: 'DEGRADED' }, lastErrorCode: 'UPSTREAM_TIMEOUT', lastErrorDetail: 'Timeout fournisseur fictif.', consecutiveFailures: 2, nextRetryAt: iso(0.1) },
  ],
  audit: [
    { id: 9901, adminUserId: 1, employerId: 5001, entityType: 'SUPPLIER', entityId: '801', action: 'SUPPLIER_GOVERNANCE_UPDATED', payload: { demo: true }, createdAt: iso(-1) },
    { id: 9902, adminUserId: 1, employerId: 5002, entityType: 'PRODUCT', entityId: '903', action: 'PRODUCT_UPDATED', payload: { demo: true }, createdAt: iso(-2) },
  ],
  operationalOrders: [
    {
      id: 7001,
      orderNumber: 'CMD-PART-DEMO-7001',
      partnerId: '801',
      partnerName: 'Dental Supply Demo',
      status: 'DRAFT',
      allowedTransitions: ['SENT_TO_PARTNER', 'CANCELLED'],
      currentTotal: 1240,
      estimatedTotal: 1240,
      recognizedRevenueAmount: 0,
      partnerReference: null,
      lines: [
        { productId: '901', name: 'Composite universel Démo', sku: 'CMP-DEMO-01', quantity: 2, unitPrice: 390, lineTotal: 780 },
        { productId: '902', name: 'Limes NiTi Test', sku: 'NITI-TEST-06', quantity: 2, unitPrice: 230, lineTotal: 460 },
      ],
    },
    {
      id: 7002,
      orderNumber: 'CMD-PART-DEMO-7002',
      partnerId: '802',
      partnerName: 'MedStock Test',
      status: 'CONFIRMED',
      allowedTransitions: ['FULFILLED', 'CANCELLED'],
      currentTotal: 2860,
      estimatedTotal: 2860,
      recognizedRevenueAmount: 286,
      partnerReference: 'SUP-TEST-8841',
      lines: [{ productId: '903', name: 'Gants nitrile Preview', sku: 'NIT-PREVIEW-M', quantity: 20, unitPrice: 143, lineTotal: 2860 }],
    },
    {
      id: 7003,
      orderNumber: 'CMD-PART-DEMO-7003',
      partnerId: '801',
      partnerName: 'Dental Supply Demo',
      status: 'FULFILLED',
      allowedTransitions: [],
      currentTotal: 940,
      estimatedTotal: 940,
      recognizedRevenueAmount: 94,
      partnerReference: 'SUP-TEST-7710',
      lines: [{ productId: '902', name: 'Limes NiTi Test', sku: 'NITI-TEST-06', quantity: 4, unitPrice: 235, lineTotal: 940 }],
    },
  ],
  financeSummary: {
    ordersCount: 3,
    matchedCount: 1,
    mismatchCount: 1,
    waitingInvoiceCount: 1,
    waitingReceiptCount: 0,
    cancelledCount: 0,
    currentOrderAmount: 5040,
    recognizedRevenueAmount: 380,
    expectedSupplierPayable: 4660,
    invoicedAmount: 4510,
    invoiceVariance: -150,
    orders: [],
  },
  operationDetails: {
    7001: { dispatch: null, procurement: null, receipts: [], reconciliation: { reconciliationStatus: 'WAITING_INVOICE', invoiceVariance: 0 } },
    7002: { dispatch: { outcome: 'SUCCEEDED', responseStatus: 201, supplierReference: 'SUP-TEST-8841' }, procurement: { supplierReference: 'SUP-TEST-8841', expectedDeliveryAt: iso(3), backorderedLines: [], note: 'Accusé fictif' }, receipts: [{ id: 1, lines: [{ productId: '903', quantityReceived: 8 }], stockSync: { status: 'APPLIED' } }], reconciliation: { reconciliationStatus: 'AMOUNT_MISMATCH', invoiceVariance: -150 } },
    7003: { dispatch: { outcome: 'SUCCEEDED', responseStatus: 201, supplierReference: 'SUP-TEST-7710' }, procurement: { supplierReference: 'SUP-TEST-7710', expectedDeliveryAt: iso(-1), backorderedLines: [], note: null }, receipts: [{ id: 2, lines: [{ productId: '902', quantityReceived: 4 }], stockSync: { status: 'APPLIED' } }], reconciliation: { reconciliationStatus: 'MATCHED', invoiceVariance: 0 } },
  },
};
