from pathlib import Path

path = Path('backend/routers/mobile_resource_bridge.py')
text = path.read_text()
old = '''def _document_scan_pdf(normalized_pages: list[bytes]) -> bytes:\n    if not normalized_pages:\n        raise HTTPException(status_code=422, detail="Le scan ne contient aucune page.")\n    images: list[Image.Image] = []\n    try:\n        for raw in normalized_pages:\n            with Image.open(BytesIO(raw)) as image:\n                images.append(image.convert('RGB').copy())\n        output = BytesIO()\n        images[0].save(\n            output,\n            format='PDF',\n            save_all=True,\n            append_images=images[1:],\n            resolution=150.0,\n        )\n        pdf = output.getvalue()\n        if not pdf.startswith(b'%PDF'):\n            raise HTTPException(status_code=422, detail="Impossible de générer le PDF scanné.")\n        return pdf\n    finally:\n        for image in images:\n            image.close()\n'''
new = '''def _document_scan_pdf(normalized_pages: list[bytes]) -> bytes:\n    if not normalized_pages:\n        raise HTTPException(status_code=422, detail="Le scan ne contient aucune page.")\n\n    # Keep pages compressed while assembling the PDF. Loading every 50 MP page\n    # as a simultaneous RGB bitmap could otherwise exceed 1 GiB at the 8-page cap.\n    import fitz\n\n    document = fitz.open()\n    try:\n        for raw in normalized_pages:\n            with Image.open(BytesIO(raw)) as image:\n                width_px, height_px = image.size\n            width_pt = max(1.0, width_px * 72.0 / 150.0)\n            height_pt = max(1.0, height_px * 72.0 / 150.0)\n            page = document.new_page(width=width_pt, height=height_pt)\n            page.insert_image(page.rect, stream=raw, keep_proportion=True)\n\n        pdf = document.tobytes(garbage=4, deflate=True)\n        if not pdf.startswith(b'%PDF'):\n            raise HTTPException(status_code=422, detail="Impossible de générer le PDF scanné.")\n        return pdf\n    finally:\n        document.close()\n'''
if text.count(old) != 1:
    raise SystemExit('M6-B memory fix anchor not unique')
path.write_text(text.replace(old, new, 1))
print('M6-B streaming PDF assembly patch materialized')
